[env]
TERM = "screen-256color"

[terminal.shell]
program = "/usr/bin/env zsh"

[font]
size = 20

[font.normal]
family = "Maple Mono"
style = "Semi Bold"

[font.bold]
family = "Maple Mono"
style = "Bold"

[font.italic]
family = "Maple Mono"
style = "Semi Bold Italic"

[colors.primary]
background = "#1d2021"
foreground = "#d4be98"

[colors.normal]
black = "#32302f"
red = "#ea6962"
green = "#a9b665"
yellow = "#d8a657"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#d4be98"

[colors.bright]
black = "#32302f"
red = "#ea6962"
green = "#a9b665"
yellow = "#d8a657"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#d4be98"

[window]
opacity = 0.8
blur = true
decorations = "none"
dynamic_padding = true

[window.padding]
x = 0
y = 0

[mouse]
hide_when_typing = true
