[sys]
packages = [
  "sudo",
  "man-db",
  "man-pages",
  "zip",
  # "entr",
  # "rsync",
  # "docker",
  # "qemu-user",
  # "qemu-user-binfmt",
]

# [desktop]
# packages = [
#   "hyprland",
#   "xorg-xwayland",
#   "hyprpaper",
#   "waybar",
#   "rofi",
#   "dolphin",
#   "zen-browser-bin",
#   "wezterm",
# ]

# [media]
# packages = ["xclip", "ffmpeg", "zathura", "mpv"]

[networking]
packages = ["wget", "ufw", "websocat"]

# [perf]
# packages = ["perf", "strace", "ltrace", "valgrind"]

[cli]
packages = ["bat", "fzf", "tree", "ripgrep", "go-yq"]

[dev]
packages = ["zsh", "starship", "tmux", "git", "neovim"]

[langs]
packages = [
  "nasm",
  "lld",
  "clang",
  "rust",
  "luajit",
  # "go",
  # "zig",
  "pypy-bin",
  # "typescript",
  # "typst",
]

[lang-tools]
packages = [
  "llvm",
  "make",
  "ninja",
  "cmake",
  "xmake",
  # "vcpkg",
  "pkgconf",
  "npm",
  # "luarocks",
  "tree-sitter-cli",
  # "hugo",
]

[lsps]
packages = [
  "lua-language-server",
  "bash-language-server",
  "rust-analyzer",
  # "gopls",
  # "typescript-language-server",
  # "zls",
  # "pyright",
  # "tinymist",
]

[formatters]
packages = [
  "stylua-bin",
  "shfmt",
  "taplo-cli",
  "yamlfmt",
  # "biome",
  # "typstyle",
  # "ruff",
]

[debuggers]
packages = ["gdb", "codelldb-bin"]
