[sys]
packages = [
  "sudo",
  "man-db",
  "man-pages",
  "zip",
  "entr",
  "rsync",
  "docker",
  "qemu-user",
  "qemu-user-binfmt",
]

[desktop]
packages = [
  "hyprland",
  "xorg-xwayland",
  "hyprpaper",
  "waybar",
  "rofi",
  "yazi",
  "zen-browser-bin",
]

[media]
packages = ["xclip", "ffmpeg", "zathura"]

[networking]
packages = ["wget", "ufw", "websocat"]

[cli]
packages = ["bat", "fzf", "tree", "ripgrep", "go-yq"]

[perf]
packages = ["perf", "strace", "ltrace", "valgrind"]

[dev]
packages = ["wezterm", "zsh", "starship", "tmux", "git", "neovim"]

[langs]
packages = ["nasm", "lld", "clang", "go", "zig", "luajit", "python", "typst"]

[lang-tools]
packages = [
  "llvm",
  "make",
  "ninja",
  "cmake",
  "xmake",
  "vcpkg",
  "pkgconf",
  "npm",
  "luarocks",
]

[lsps]
packages = [
  "lua-language-server",
  "bash-language-server",
  "rust-analyzer",
  "gopls",
  "typescript-language-server",
  "zls",
  "pyright",
  "tinymist",
]

[formatters]
packages = [
  "biome",
  "stylua-bin",
  "shfmt",
  "taplo-cli",
  "yamlfmt",
  "typstyle",
  "ruff",
]

[debuggers]
packages = ["gdb", "codelldb-bin"]
